header = "// SPDX-License-Identifier: LGPL-2.1-or-later"
sys_includes = ["stddef.h", "stdint.h", "stdlib.h"]
no_includes = true
include_guard = "AUDIOSCROBLLER_H"
tab_width = 4
language = "C"
documentation_style = "C"
style = "type"
cpp_compat = true

[export]
item_types = ["enums", "structs", "unions", "typedefs", "opaque", "functions"]

[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true
