[package]
name = "inflate-rs"
version = "0.1.0"
license = "LGPL-2.1-or-later"
edition = "2021"

[dependencies]
flate2 = "1.0"
vlcrs-core = { workspace = true }
vlcrs-core-macros = { workspace = true }
