[package]
name = "inflate_rust"
version = "0.1.0"
authors = ["Johan \"enulp\" Pardo <contact@enulp.eu>"]
edition = "2018"
license = "LGPL-2.1-or-later"

[dependencies]
vlccore_sys = {path = "../../../src/vlccore_sys"}
flate2 = "1.0.18"
libc = "0.2"

[lib]
name = "inflate_rust"
